version: '3.3'
services:
  rstudio-data-transformation:
    build: .
    ports:
      - "8788:8787"
    volumes:
      - ..:/home/rstudio/data-transformation
    environment: 
      DISABLE_AUTH: "true"
